#!/usr/bin/env python3
"""Build snippets/css-overrides.liquid from its documented source (bd hairmnl-theme-958r.7).

WHY
---
snippets/css-overrides.liquid is inlined into a <style> in <head> on EVERY page, so every byte is
per-pageview cost. Measured 2026-08-06: 96.3 KB raw / 32.0 KB gzipped, of which 72% is comments.
For scale, the entire critical-css payload is 8.2 KB gzipped.

Stripping comments and collapsing whitespace takes it to ~8.3 KB gzipped — a ~24 KB saving on every
page. But the comments are not noise: they are the bug-history record for a file that has caused
live regressions, and 18 of them are `kt0-OK` acknowledgements that the CSS containment lint treats
as human sign-off. Deleting them in place would throw away both.

Hence a source/build split:
  os2-migration/css-overrides.source.liquid   the documented source. Edit THIS.
  snippets/css-overrides.liquid               generated, minified, shipped. Do NOT edit.
os2-migration/ is not one of Shopify's theme directories, so the source is never uploaded; the
generated file keeps the original path, so `{% render 'css-overrides' %}` and the snippet-wiring
lint are untouched.

WHY kt0-OK ACKNOWLEDGEMENTS ARE KEPT IN THE OUTPUT
--------------------------------------------------
Stripping them too would save a further ~3.6 KB gzipped, and it was tempting. They are kept because:
  1. scripts/check-overlay-css.py and check-critical-css-coverage.py both scan the SHIPPED snippet.
     Keeping the acks means neither lint needs to change and neither can be fooled by a build step —
     fewer moving parts in the safety mechanism.
  2. That lint exists because of two live regressions (2026-05-11 sticky header, 2026-05-12 Reamaze
     chat hidden for ~10 days). Shipping the acknowledgements means the sign-off is verifiable on the
     live page, not only in a repo file the build could drift from.
  3. It still captures 87% of the available saving.

USAGE
    python3 scripts/build-css-overrides.py           # rebuild the snippet from source
    python3 scripts/build-css-overrides.py --check   # verify the snippet is in sync (CI / pre-push)

--check exits 1 if the generated file differs from a fresh build, so the two can never drift.
"""

from __future__ import annotations

import gzip
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "os2-migration" / "css-overrides.source.liquid"
OUTPUT = REPO / "snippets" / "css-overrides.liquid"

KEEP_TOKENS = ("kt0-OK", "ccc-OK")
BANNER = ("/*! GENERATED by scripts/build-css-overrides.py from "
          "os2-migration/css-overrides.source.liquid — DO NOT EDIT THIS FILE. "
          "Edit the source and rebuild; CI verifies they match. bd 958r.7 */")


def minify(src: str) -> str:
    """Strip comments and collapse whitespace, preserving acknowledgement comments.

    Deliberately conservative. The source is pure CSS inside a <style> wrapper — verified 2026-08-06
    to contain zero Liquid tags, zero url(), zero data: URIs and zero brace-bearing content strings —
    so the aggressive cases that usually break naive CSS minifiers do not arise here. build_and_check()
    proves equivalence rule-by-rule anyway.
    """
    m = re.match(r"\s*<style>(.*)</style>\s*\Z", src, flags=re.DOTALL)
    if not m:
        raise SystemExit("ERROR: source is not a single <style>…</style> block")
    css = m.group(1)

    def drop_comment(mm: re.Match) -> str:
        text = mm.group(0)
        return text if any(t in text for t in KEEP_TOKENS) else ""

    css = re.sub(r"/\*.*?\*/", drop_comment, css, flags=re.DOTALL)

    # Newlines between selector parts are descendant combinators, so they must become spaces —
    # never be deleted outright. Collapse first, then squeeze around punctuation.
    css = re.sub(r"\s+", " ", css)
    css = re.sub(r"\s*([{};,])\s*", r"\1", css)
    # `:` is only safe to squeeze on the VALUE side; squeezing before it would corrupt
    # `a :hover`-style selectors, so only the trailing space is removed.
    css = re.sub(r":\s+", ":", css)
    css = re.sub(r";+\}", "}", css)
    css = re.sub(r"\s*>\s*", ">", css)
    return f"<style>{BANNER}{css.strip()}</style>\n"


# ------------------------------------------------------------------ equivalence verification

def rules_with_context(css: str, ctx: tuple = ()):
    """(selector, body, at-rule context) — keeps @media context so two rules with the same
    selector under different breakpoints are never treated as equal."""
    src = re.sub(r"/\*.*?\*/", lambda m: " " * len(m.group(0)), css, flags=re.DOTALL)
    i, n, sel_start = 0, len(src), 0
    while i < n:
        if src[i] == "{":
            selector = src[sel_start:i].strip()
            depth, j = 1, i + 1
            while j < n and depth:
                if src[j] == "{":
                    depth += 1
                elif src[j] == "}":
                    depth -= 1
                j += 1
            body = src[i + 1:j - 1]
            low = selector.lstrip().lower()
            if low.startswith("@") and not low.startswith("@font-face") and "{" in body:
                yield from rules_with_context(body, ctx + (" ".join(selector.split()),))
            else:
                yield " ".join(selector.split()), body, ctx
            i, sel_start = j, j
            continue
        if src[i] == "}":
            sel_start = i + 1
        i += 1


def _canon(text: str) -> str:
    """Collapse formatting that CSS treats as insignificant, so the comparison tests MEANING.

    Whitespace after a comma and around a colon inside an at-rule preamble is optional in CSS, so
    `rgba(0, 0, 0, .06)` and `rgba(0,0,0,.06)`, or `(min-width: 768px)` and `(min-width:768px)`, are
    the same declaration. Note what is deliberately NOT normalised: whitespace around `-` and `+`,
    which is REQUIRED inside calc() — `calc(100vw - 1180px)` and `calc(100vw-1180px)` mean different
    things, so a minifier that ate those spaces must still fail this check.
    """
    t = " ".join(text.split()).lower()
    t = re.sub(r"\s*,\s*", ",", t)
    t = re.sub(r":\s+", ":", t)
    return t


def normalise(css: str):
    """Canonical (context, selector, ordered declarations) tuples for comparison."""
    out = []
    for sel, body, ctx in rules_with_context(css):
        decls = []
        for d in body.split(";"):
            if ":" in d:
                k, _, v = d.partition(":")
                decls.append((k.strip().lower(), _canon(v)))
        s = re.sub(r"\s*([>+~])\s*", r"\1", _canon(sel))
        out.append((tuple(_canon(c) for c in ctx), s, tuple(decls)))
    return out


def build_and_check() -> tuple[str, list[str]]:
    src = SOURCE.read_text(encoding="utf-8")
    built = minify(src)
    problems = []
    a, b = normalise(src), normalise(built)
    if len(a) != len(b):
        problems.append(f"rule count changed: source {len(a)} -> built {len(b)}")
    for i, (ra, rb) in enumerate(zip(a, b)):
        if ra != rb:
            problems.append(f"rule {i} differs:\n    source: {ra}\n    built : {rb}")
            if len(problems) > 5:
                break
    return built, problems


def main(argv: list[str]) -> int:
    if not SOURCE.is_file():
        print(f"ERROR: source not found at {SOURCE}", file=sys.stderr)
        return 2
    built, problems = build_and_check()
    if problems:
        print("BUILD ABORTED — minified output is not equivalent to the source:", file=sys.stderr)
        for p in problems:
            print("  " + p, file=sys.stderr)
        return 2

    src_bytes = SOURCE.read_text(encoding="utf-8").encode()
    out_bytes = built.encode()
    stats = (f"  source {len(src_bytes)/1024:6.1f} KB raw / {len(gzip.compress(src_bytes))/1024:5.1f} KB gz\n"
             f"  built  {len(out_bytes)/1024:6.1f} KB raw / {len(gzip.compress(out_bytes))/1024:5.1f} KB gz\n"
             f"  saved  {(len(gzip.compress(src_bytes))-len(gzip.compress(out_bytes)))/1024:6.1f} KB gzipped per pageview")

    if "--check" in argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != built:
            print("FAIL: snippets/css-overrides.liquid is out of sync with its source.", file=sys.stderr)
            print("      Run: python3 scripts/build-css-overrides.py", file=sys.stderr)
            return 1
        print("OK: css-overrides snippet is in sync with its source")
        print(stats)
        return 0

    OUTPUT.write_text(built, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    print(stats)
    print(f"  rules verified equivalent: {len(normalise(built))}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
